### PR TITLE
Add free floating dynamics

### PR DESCRIPTION
**Pull request by Sciancisco**
see issue #275

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/276)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/276)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @Ipuch, @pariterre, and @Sciancisco)

___
*[`include/RigidBody/Joints.h` line 914 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8t-r1-914:-N3UMXwE7JngBW96tXBJ:b6njvug) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/include/RigidBody/Joints.h#L914)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Maybe it cannot be bound in python. Should we use a string instead @pariterre?
</blockquote></details>

There is no need (unless you feel otherwise) to support multiple linearSolver. They will all return the same answer and we know in advance the structure of the problem, so we can make choices before hand. That said, if you want to support, you will have to create a derived (probably empty) class of `LinearSolver`
___
*[`src/RigidBody/Joints.cpp` line 1460 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8u-r1-1460:-N3UN0k45K8TXNcdg_31:b33mdo0) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/src/RigidBody/Joints.cpp#L1460)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

You should call it massMatrixRR as it is the matrix related to the root dofs.
</blockquote></details>

why not `massMatrixRoot` then? what does RR mean?
___
*[`src/RigidBody/Joints.cpp` line 1471 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3UNAt2-L_3m2CvXDbI:-N3UNAt2-L_3m2CvXDbJ:b-49bxuj) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/src/RigidBody/Joints.cpp#L1471)):*
> ```cpp
>     QDDotR = massMatrix.inverse() * -NLEffects.block(0, 0, this->nbRoot(), 1);
> #else
>     switch (linearSolver) {
> ```

As I said, I do not really see the point of supporting multiple solvers, but you can if you think it makes sense



_Code quote:_
```cpp
    switch (linearSolver) {
        case (RigidBodyDynamics::Math::LinearSolverPartialPivLU) :
          QDDotR = massMatrix.partialPivLu().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        case (RigidBodyDynamics::Math::LinearSolverColPivHouseholderQR) :
          QDDotR = massMatrix.colPivHouseholderQr().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        case (RigidBodyDynamics::Math::LinearSolverHouseholderQR) :
          QDDotR = massMatrix.householderQr().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        case (RigidBodyDynamics::Math::LinearSolverLLT) :
          QDDotR = massMatrix.llt().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        default:
          LOG << "Error: Invalid linear solver: " << linearSolver << std::endl;
          assert (0);
          break;
    }
```
___
*[`test/test_rigidbody.cpp` line 2014 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8v-r1-2014:-N3UNMVS25Pi-1kMvwPf:b-lbut5x) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/test/test_rigidbody.cpp#L2014)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I left this to @pariterre 
</blockquote></details>

What do you mean?
___
*[`test/test_rigidbody.cpp` line 2063 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8v-r1-2063:-N3UNUMmABsk9wwuMJH2:bb7od0r) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/test/test_rigidbody.cpp#L2063)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

@pariterre  same
</blockquote></details>

same
___
*[`test/test_rigidbody.cpp` line 2077 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8v-r1-2077:-N3UNQdo6l4z9gBQ_8u_:beeslgj) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/test/test_rigidbody.cpp#L2077)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Probably not (if we remove them)

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/276)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @Ipuch, @pariterre, and @Sciancisco)

___
*[`src/RigidBody/Joints.cpp` line 1490 at r2](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3UcRODBB8i88cLRKsu:-N48Ubt98W9rYXHyc778:b2nhswv) ([raw file](https://github.com/pyomeca/biorbd/blob/3c7f7d4eb1868f1fa032e8b49991751c8a0a6398/src/RigidBody/Joints.cpp#L1490)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

Done.
By the same token, should I also change QDDotJ to QJointsDDot?
</blockquote></details>

Yep
___
*[`src/RigidBody/Joints.cpp` line 1465 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48SgiEBhqD0YeiH08J:-N48SgiEBhqD0YeiH08K:bbeblyt) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/src/RigidBody/Joints.cpp#L1465)):*
> ```cpp
>     QDDot.block(this->nbRoot(), 0, this->nbQddot()-this->nbRoot(), 1) = QDDotJ;
> 
>     NLEffects = InverseDynamics(Q, QDot, QDDot, nullptr, nullptr);  // not exactly the NLEffects
> ```

Please change it to: ``MassMatrixNlEffects` then



_Code quote:_
```cpp
 // not exactly the NLEffects
```
___
*[`test/test_rigidbody.cpp` line 2014 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8v-r1-2014:-N48UgKfE9yyr7qwNedj:bpqbktk) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/test/test_rigidbody.cpp#L2014)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

How would I create QDDotJ with a custom size?
</blockquote></details>

This does not really make sense as it won't be able to use it... QDDot size should be the same as QDot 
___
*[`test/test_rigidbody.cpp` line 2012 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48VUU0Al66b8Ne_cK0:-N48VUU0Al66b8Ne_cK1:be9a7vm) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/test/test_rigidbody.cpp#L2012)):*
> ```cpp
>     {
>         Model model(modelPathForGeneralTesting);
>         rigidbody::GeneralizedCoordinates Q(model);
> ```

This can't be. It has to be DECLARE...



_Code quote:_
```cpp
        rigidbody::GeneralizedCoordinates Q(model);
        rigidbody::GeneralizedVelocity QDot(model);
        rigidbody::GeneralizedAcceleration QDDotJ(model.nbQddot() - model.nbRoot());
```
___
*[`test/test_rigidbody.cpp` line 2047 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48UyBK3IylVZXcGIso:-N48UyBK3IylVZXcGIsp:b9hkbqu) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/test/test_rigidbody.cpp#L2047)):*
> ```cpp
>         };
> 
>         QRootDDot = model.ForwardDynamicsFreeFloatingBase(Q, QDot, QDDotJ);
> ```

This should be CALL_BIORBD... otherwise the Casadi backend will fail, if you need to pass 4 arguments create the 4ARGS
___
*[`test/test_rigidbody.cpp` line 2059 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48VFpA2eobrc-hF2Eu:-N48VFpA2eobrc-hF2Ev:b90u6y8) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/test/test_rigidbody.cpp#L2059)):*
> ```cpp
>         Model model(modelPathForGeneralTesting);
>         rigidbody::GeneralizedCoordinates Q(model);
>         rigidbody::GeneralizedVelocity QDot(model);
> ```

This can't be. It has top be DECLARE...



_Code quote:_
```cpp
        rigidbody::GeneralizedCoordinates Q(model);
        rigidbody::GeneralizedVelocity QDot(model);
        rigidbody::GeneralizedAcceleration QDDotJ(model);  // simulate possible mistake
```

**Review by Sciancisco — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/276)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`include/RigidBody/Joints.h` line 914 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8t-r1-914:-N4CsvmnEcGKQfPGo5cj:b-lbe5c1) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/include/RigidBody/Joints.h#L914)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

There is no need (unless you feel otherwise) to support multiple linearSolver. They will all return the same answer and we know in advance the structure of the problem, so we can make choices before hand. That said, if you want to support, you will have to create a derived (probably empty) class of `LinearSolver`
</blockquote></details>

Done.

Removed all but LLT.
___
*[`src/RigidBody/Joints.cpp` line 1490 at r2](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3UcRODBB8i88cLRKsu:-N48o21Q1cN6P4GiMGNQ:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/3c7f7d4eb1868f1fa032e8b49991751c8a0a6398/src/RigidBody/Joints.cpp#L1490)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Yep
</blockquote></details>

Done.
___
*[`src/RigidBody/Joints.cpp` line 1465 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48SgiEBhqD0YeiH08J:-N48o2s95j99c4GbzXJO:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/src/RigidBody/Joints.cpp#L1465)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please change it to: ``MassMatrixNlEffects` then
</blockquote></details>

Done.
___
*[`test/test_rigidbody.cpp` line 2014 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8v-r1-2014:-N4Ctbeb7nsWxpaq6vPd:b-d96b4) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/test/test_rigidbody.cpp#L2014)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This does not really make sense as it won't be able to use it... QDDot size should be the same as QDot 
</blockquote></details>

Done.

Added new macro `DECLARE_GENERALIZED(Type, varname, nbElements)`
___
*[`test/test_rigidbody.cpp` line 2077 at r1](https://reviewable.io/reviews/pyomeca/biorbd/276#-N3QTHwMfDD6rwRCkQ8v-r1-2077:-N4CtDcx96dOd4vprvOq:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/3ef0aca0359905e7f2f7dac07e74fe2389221321/test/test_rigidbody.cpp#L2077)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Probably not (if we remove them)
</blockquote></details>

Done.
___
*[`test/test_rigidbody.cpp` line 2012 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48VUU0Al66b8Ne_cK0:-N4Ct_BSDtqNMajnHTGw:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/test/test_rigidbody.cpp#L2012)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This can't be. It has to be DECLARE...
</blockquote></details>

Done.
___
*[`test/test_rigidbody.cpp` line 2047 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48UyBK3IylVZXcGIso:-N4CtXjS4BNYrax53MRo:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/test/test_rigidbody.cpp#L2047)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be CALL_BIORBD... otherwise the Casadi backend will fail, if you need to pass 4 arguments create the 4ARGS
</blockquote></details>

Done.
___
*[`test/test_rigidbody.cpp` line 2059 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48VFpA2eobrc-hF2Eu:-N4D4iJm4D-LaRcTCA5L:bl6szcb) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/test/test_rigidbody.cpp#L2059)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This can't be. It has top be DECLARE...
</blockquote></details>

DECLARE... doesn't work with `EXPECT_THROW` with CasADi

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/276)* status: all files reviewed, 8 unresolved discussions (waiting on @Ipuch and @Sciancisco)

___
*[`include/biorbdConfig.h.in` line 100 at r10](https://reviewable.io/reviews/pyomeca/biorbd/276#-N4hZa9I9dGJ-2OQjhko:-N4hZa9JAai3yW0J_HyU:bufyas0) ([raw file](https://github.com/pyomeca/biorbd/blob/f54f6ab9b54db2f05f4c26306cc31bdbb4a2295a/include/biorbdConfig.h.in#L100)):*
> ```
>     casadi::DM varname(model.nbGeneralizedTorque(), 1);\
>     BIORBD_NAMESPACE::rigidbody::GeneralizedTorque varname##_sym(casadi::MX::sym(#varname, model.nbGeneralizedTorque(), 1));
> #define DECLARE_GENERALIZED(Type, varname, nbElements) \
> ```

`DECLARE_GENERALIZED_VECTOR` ? `DECLARE_GENERALIZED_GENERIC`? `DECLARE_GENERALIZED_OF_TYPE`?
___
*[`src/RigidBody/Joints.cpp` line 1469 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48fpKCBoRWWV6FZKHg:-N48fpKCBoRWWV6FZKHh:bczqjko) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/src/RigidBody/Joints.cpp#L1469)):*
> ```cpp
> #ifdef BIORBD_USE_CASADI_MATH
>     auto linsol = casadi::Linsol("linsol", "ldl", massMatrixRoot.sparsity());
>     QRootDDot = linsol.solve(massMatrixRoot, -NLEffects.block(0, 0, this->nbRoot(), 1));
> ```

Expand these matrices



_Code quote:_
```cpp
    auto linsol = casadi::Linsol("linsol", "ldl", massMatrixRoot.sparsity());
    QRootDDot = linsol.solve(massMatrixRoot, -NLEffects.block(0, 0, this->nbRoot(), 1));
```
___
*[`src/RigidBody/Joints.cpp` line 1479 at r7](https://reviewable.io/reviews/pyomeca/biorbd/276#-N48faz-D-9nQIV2o3kj:-N48faz-D-9nQIV2o3kk:b-6xlk9x) ([raw file](https://github.com/pyomeca/biorbd/blob/c849c1fdc6bd57ffb9a5439e3ec098d38aebf7e2/src/RigidBody/Joints.cpp#L1479)):*
> ```cpp
>           break;
>         case (RigidBodyDynamics::Math::LinearSolverHouseholderQR) :
>           QRootDDot = massMatrixRoot.householderQr().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
> ```

Time fastest and select this one



_Code quote:_
```cpp
    switch (linearSolver) {
        case (RigidBodyDynamics::Math::LinearSolverPartialPivLU) :
          QRootDDot = massMatrixRoot.partialPivLu().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        case (RigidBodyDynamics::Math::LinearSolverColPivHouseholderQR) :
          QRootDDot = massMatrixRoot.colPivHouseholderQr().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        case (RigidBodyDynamics::Math::LinearSolverHouseholderQR) :
          QRootDDot = massMatrixRoot.householderQr().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        case (RigidBodyDynamics::Math::LinearSolverLLT) :
          QRootDDot = massMatrixRoot.llt().solve(-NLEffects.block(0, 0, this->nbRoot(), 1));
          break;
        default:
          utils::Error::raise("Unsupported linear solver.");
          break;
```

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/276#-:-N4hzHPA4gR_9H8XPlIm:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch)

**Pull request merged**
