### PR TITLE
Jacobian of segment rotation matrix

### PR DESCRIPTION
**Pull request by Ipuch**
a PR to get jacobian rotation matrix with the API

- - -
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/284)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/284)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`test/test_rigidbody.cpp` line 972 at r2](https://reviewable.io/reviews/pyomeca/biorbd/284#-N9D4tPM9osLTI6nE_jn:-N9D4tPM9osLTI6nE_jo:b8rxqnj) ([raw file](https://github.com/pyomeca/biorbd/blob/f777ab0a16620be4b1b6c6d5674fa59d48badf8a/test/test_rigidbody.cpp#L972)):*
> ```cpp
>         Model model(modelPathForGeneralTesting);
>         EXPECT_EQ(model.getBodyBiorbdIdToRbdlId(0),3);
>         EXPECT_EQ(model.getBodyBiorbdIdToRbdlId(1),2147483647);
> ```

INT_MAX



_Code quote:_
```cpp
2147483647
```

**Comment by Ipuch** [comment]
ready to merge :)

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Review by pariterre — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/284#-:-N9IGoi24kQSuspWfDGo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
