### PR TITLE
Move actuators and muscles in "internalforce" namespace

### PR DESCRIPTION
**Pull request by aceglia**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/301)

### CODE REVIEW

**Comment by aceglia** [comment]
@pariterre m_type missing in muscle constructor was the issue, it works well now on python and c++. It's RTR.

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 99 of 104 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/301)* status: all files reviewed, 4 unresolved discussions (waiting on @aceglia)

___
*[`examples/WrappingObjectsExample.cpp` line 38 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ1r24015kiS4GiffX:-NFQ1r24015kiS4GiffY:b-9y1r7d) ([raw file](https://github.com/pyomeca/biorbd/blob/c1b97dc865427bc0a27bbb40d01016a260ca1e13/examples/WrappingObjectsExample.cpp#L38)):*
> ```cpp
>     auto Tau = model.muscularJointTorque(states, Q, Qdot);
> 
>     class Compound;
> ```

This is probably not useful
___
*[`test/CMakeLists.txt` line 59 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ7ehx8eXN5nDvUnHc:-NFQ7ehx8eXN5nDvUnHd:b-xveic7) ([raw file](https://github.com/pyomeca/biorbd/blob/4fd83b1c75b2247d9dbbdab835aa104e3df5f3a6/test/CMakeLists.txt#L59)):*
> ```CMake
>     "${CMAKE_SOURCE_DIR}/test/test_rigidbody.cpp"
>     "${CMAKE_SOURCE_DIR}/test/test_utils.cpp"
>     "${CMAKE_SOURCE_DIR}/test/test_actuators.cpp"
> ```

Is this expected
___
*[`src/InternalForces/Compound.cpp` line 7 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ4JH47ZqxOa6AEvES:-NFQ4JH47ZqxOa6AEvET:blqa24l) ([raw file](https://github.com/pyomeca/biorbd/blob/c1b97dc865427bc0a27bbb40d01016a260ca1e13/src/InternalForces/Compound.cpp#L7)):*
> ```cpp
> #include "Utils/Vector3d.h"
> #include "RigidBody/GeneralizedCoordinates.h"
> #include "InternalForces/PathModifiers.h"
> ```

Just noticed here, but the file is "InternalForces" while the namespace is "internalforce" I think agree more with the plural from the folder name. Also, I just had a look, it seems snake_case is canonical for namespace, so I would suggest: `internal_forces::...` as namespace (just a quick search and replace, hopefully :P)
___
*[`src/InternalForces/Muscles/StaticOptimization.cpp` line 2 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ7ScyBjIWSo5Y4PU0:-NFQ7ScyBjIWSo5Y4PU1:b8q3zwk) ([raw file](https://github.com/pyomeca/biorbd/blob/c1b97dc865427bc0a27bbb40d01016a260ca1e13/src/InternalForces/Muscles/StaticOptimization.cpp#L2)):*
> ```cpp
> #define BIORBD_API_EXPORTS
> #include "InternalForces/Muscles/StaticOptimization.h"
> ```

Put it with the Internal 10 includes below

**Review by aceglia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/301)* status: 16 of 105 files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`examples/WrappingObjectsExample.cpp` line 38 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ1r24015kiS4GiffX:-NFQ90fH3LrJKYaQ2aXl:ba3dfob) ([raw file](https://github.com/pyomeca/biorbd/blob/c1b97dc865427bc0a27bbb40d01016a260ca1e13/examples/WrappingObjectsExample.cpp#L38)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is probably not useful
</blockquote></details>

Removed
___
*[`test/CMakeLists.txt` line 59 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ7ehx8eXN5nDvUnHc:-NFQBrKk1OPGBLyvmH_c:bmf2ixt) ([raw file](https://github.com/pyomeca/biorbd/blob/4fd83b1c75b2247d9dbbdab835aa104e3df5f3a6/test/CMakeLists.txt#L59)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is this expected
</blockquote></details>

What do you mean ? Test are build only if module actuator. 
___
*[`src/InternalForces/Compound.cpp` line 7 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ4JH47ZqxOa6AEvES:-NFQ9E6U844MrzbsHzF3:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/c1b97dc865427bc0a27bbb40d01016a260ca1e13/src/InternalForces/Compound.cpp#L7)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Just noticed here, but the file is "InternalForces" while the namespace is "internalforce" I think agree more with the plural from the folder name. Also, I just had a look, it seems snake_case is canonical for namespace, so I would suggest: `internal_forces::...` as namespace (just a quick search and replace, hopefully :P)
</blockquote></details>

Done.
___
*[`src/InternalForces/Muscles/StaticOptimization.cpp` line 2 at r2](https://reviewable.io/reviews/pyomeca/biorbd/301#-NFQ7ScyBjIWSo5Y4PU0:-NFQBGW63iVDPmUbEwDy:bpzjo08) ([raw file](https://github.com/pyomeca/biorbd/blob/c1b97dc865427bc0a27bbb40d01016a260ca1e13/src/InternalForces/Muscles/StaticOptimization.cpp#L2)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put it with the Internal 10 includes below
</blockquote></details>

I think it's done if I understood well

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 89 of 89 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/301#-:-NFQOsl80l9dsanC9mxk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aceglia)

**Comment by pariterre** [comment]
@aceglia 
Windows fails with the installed version using Casadi Backend, if you need help to debug, ping me!

**Comment by pariterre** [comment]
@aceglia 
Tests fails so renaming to normal name!

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/301#-:-NFV8_zj3vHaHSNpy9of:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @aceglia)

**Comment by pariterre** [comment]
All tests now passes Pushing the 1.9.6 version! :)

**Pull request merged**
