### PR TITLE
[RTR] loop constraints

### PR DESCRIPTION
**Pull request by Ipuch**
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/323)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/323)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @Ipuch)

___
*[`include/RigidBody/Contacts.h` line 111 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6yFoGDF6fPzGfxxWD:-NQ6yFoGDF6fPzGfxxWE:b-6a03tr) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/include/RigidBody/Contacts.h#L111)):*
> ```objc
>     /// \param updateKin If the model should be updated
>     ///
>     std::vector< RigidBodyDynamics::Math::SpatialVector > calcLoopConstraintForces(
> ```

Please output BIORBD SpatialVector (without space around)



_Code quote:_
```objc
RigidBodyDynamics::Math::SpatialVector
```
___
*[`src/RigidBody/Contacts.cpp` line 133 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6z4s162FH3kPGiUSD:-NQ6z4s162FH3kPGiUSE:b-oqoyuq) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L133)):*
> ```cpp
> {
>     // retrieve the model
>     rigidbody::Joints &model = dynamic_cast<rigidbody::Joints &>
> ```

move this (this) to the previous line



_Code quote:_
```cpp
(*this);
```
___
*[`src/RigidBody/Contacts.cpp` line 159 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ7-3BJ8cBR4P15yr-h:-NQ7-3BJ8cBR4P15yr-i:b1aqlgc) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L159)):*
> ```cpp
>         // Assuming that this is also a Joints type (via BiorbdModel)
>         const rigidbody::Joints &model =
>             dynamic_cast<rigidbody::Joints &>(*this);
> ```

This is not useful



_Code quote:_
```cpp
        const rigidbody::Joints &model =
            dynamic_cast<rigidbody::Joints &>(*this);
```
___
*[`src/RigidBody/Contacts.cpp` line 163 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6zL-t4BmEOp2PKMMg:-NQ6zL-t4BmEOp2PKMMh:b-k6yt4c) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L163)):*
> ```cpp
>         *m_isBinded = true;
>     }
>     (*this).calcForces(
> ```

this->



_Code quote:_
```cpp
(*this)
```
___
*[`src/RigidBody/Contacts.cpp` line 165 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6zJ4g6onbG6txaVVz:-NQ6zJ4g6onbG6txaVW-:b-8ne0bh) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L165)):*
> ```cpp
>     (*this).calcForces(
>                 loopConstraintId,
>                 model,
> ```

*this



_Code quote:_
```cpp
model
```
___
*[`src/RigidBody/Contacts.cpp` line 145 at r2](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ7209zBqmjE2fJxBt3:-NQ720A-4g4d_5FxEjee:by4l1th) ([raw file](https://github.com/pyomeca/biorbd/blob/58cdc1a4d11f2a98eeaa7e32dab717c767341924/src/RigidBody/Contacts.cpp#L145)):*
> ```cpp
> #ifdef BIORBD_USE_CASADI_MATH
>     updateKin = true;
> #endif
> ```

Remove this parameters



_Code quote:_
```cpp
#ifdef BIORBD_USE_CASADI_MATH
    updateKin = true;
#endif
```

**Review by Ipuch — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/323#-:-NQ7VyjtBCLD3kT9CB5C:b-896fix)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`include/RigidBody/Contacts.h` line 111 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6yFoGDF6fPzGfxxWD:-NQ7W0-q3ginKyrIqkqg:bb6un1j) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/include/RigidBody/Contacts.h#L111)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please output BIORBD SpatialVector (without space around)
</blockquote></details>

Done
___
*[`src/RigidBody/Contacts.cpp` line 133 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6z4s162FH3kPGiUSD:-NQ7W0vW1FkQeQ-9YpI9:bb6un1j) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L133)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move this (this) to the previous line
</blockquote></details>

Done
___
*[`src/RigidBody/Contacts.cpp` line 159 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ7-3BJ8cBR4P15yr-h:-NQ7W3tQ44ZPkiuormuM:bb6un1j) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L159)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is not useful
</blockquote></details>

Done
___
*[`src/RigidBody/Contacts.cpp` line 163 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6zL-t4BmEOp2PKMMg:-NQ7W4RlC8FZPzmkK-MP:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L163)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

this->
</blockquote></details>

Done.
___
*[`src/RigidBody/Contacts.cpp` line 165 at r1](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ6zJ4g6onbG6txaVVz:-NQ7W4zSD3Ci2V6Z1AXS:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/d01ba7bfb6a7f168ab9038a1c81af9de1b96e452/src/RigidBody/Contacts.cpp#L165)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

*this
</blockquote></details>

Done.
___
*[`src/RigidBody/Contacts.cpp` line 145 at r2](https://reviewable.io/reviews/pyomeca/biorbd/323#-NQ7209zBqmjE2fJxBt3:-NQ7W3Mv5qQnsG7elk8D:ban9ryb) ([raw file](https://github.com/pyomeca/biorbd/blob/58cdc1a4d11f2a98eeaa7e32dab717c767341924/src/RigidBody/Contacts.cpp#L145)):*
> Done
Done

**Comment by Ipuch** [comment]
Do I need a 4args to test the new function ?

**Comment by pariterre** [comment]
To test for external forces, yes, but it is not exactly trivial to do, I can create one if you want to test for external forces!

**Comment by Ipuch** [comment]
@pariterre okay to me ;)

**Review by pariterre — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/323#-:-NQeoGDU6nOd4AFKka0T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Comment by Ipuch** [comment]
@pariterre

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/323#-:-NTVEFLe6XV7Jf2kQ5LN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Pull request merged**
