### PR TITLE
[RTR] eulerDot - body velocity tranformation

### PR DESCRIPTION
**Pull request by EveCharbie**
issue : Verify conversion from rotation matrix to euler angles #165

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/263)

### CODE REVIEW

**Comment by EveCharbie** [comment]
@pariterre I am not done yet, but I need help with how to write this :
`Matrix3d velocity_matrix = velocityMatrix(euler, seq).colPivHouseholderQr();`

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/263)* status: all files reviewed, 4 unresolved discussions (waiting on @EveCharbie)

___
*[include/Utils/Quaternion.h, line 6 at r1](https://reviewable.io/reviews/pyomeca/biorbd/263#-MxtkG1T8J24vcKVB0BM:-MxtkG1T8J24vcKVB0BN:b-9tpjsu) ([raw file](https://github.com/pyomeca/biorbd/blob/62bdac9760e73cc5394fcc69d73004c01d68d685/include/Utils/Quaternion.h#L6)):*
> ```objc
> #include <memory>
> #include "Utils/Vector3d.h"
> #include "Utils/Matrix3d.h"
> ```

Is this necessary? Use the forward declaration (few lines below) if possible (and move the include to the cpp file).
___
*[src/Utils/Quaternion.cpp, line 351 at r1](https://reviewable.io/reviews/pyomeca/biorbd/263#-Mxtkm555Zu62kL1KGhL:-Mxtkm555Zu62kL1KGhM:b-3d0h07) ([raw file](https://github.com/pyomeca/biorbd/blob/62bdac9760e73cc5394fcc69d73004c01d68d685/src/Utils/Quaternion.cpp#L351)):*
> ```cpp
>     }
>     
>     utils::Matrix3d unit_vectors_matrix;
> ```

Please use `camelCase` (instead of `snake_case`) variable names in C++
___
*[src/Utils/Quaternion.cpp, line 362 at r1](https://reviewable.io/reviews/pyomeca/biorbd/263#-MxtlRQW6Y2ITNw21tBO:-MxtlRQW6Y2ITNw21tBP:bzbocxc) ([raw file](https://github.com/pyomeca/biorbd/blob/62bdac9760e73cc5394fcc69d73004c01d68d685/src/Utils/Quaternion.cpp#L362)):*
> ```cpp
>     rotation_2[0] = euler[0];
>     rotation_2[1] = euler[1];
>     utils::Vector3d Rot_mat_1 = utils::Rotation::Rotation::fromEulerAngles(rotation_1, seq);
> ```

Is there a reason to copy all this suff?
___
*[src/Utils/Quaternion.cpp, line 377 at r1](https://reviewable.io/reviews/pyomeca/biorbd/263#-MxtkzRN-OK3GkFzs5Vb:-MxtkzRN-OK3GkFzs5Vc:b-dz0ld0) ([raw file](https://github.com/pyomeca/biorbd/blob/62bdac9760e73cc5394fcc69d73004c01d68d685/src/Utils/Quaternion.cpp#L377)):*
> ```cpp
>     velocity_matrix(i, 1) = temp_vectors_for_matrix_1[i];
>     velocity_matrix(i, 2) = temp_vectors_for_matrix_2[i];
>     }
> ```

Indent the inside of the for loop.
That said, it feels you just copy stuff from three lines before? Why don't use the .block(x, x, x, x) method?



_Code quote:_
```cpp
    velocity_matrix(i, 0) = temp_vectors_for_matrix_0[i];
    velocity_matrix(i, 1) = temp_vectors_for_matrix_1[i];
    velocity_matrix(i, 2) = temp_vectors_for_matrix_2[i];
```

**Comment by mickaelbegon** [comment]
@pariterre, if you have time, could you work with @EveCharbie on the PR? It is not urgent nor a priority

**Comment by pariterre** [comment]
@EveCharbie Please confirm the current code is what correct :)

**Comment by EveCharbie** [comment]
@pariterre : Yes looks fine, thanks :)

**Review by pariterre — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Comment by pariterre** [comment]
@EveCharbie 
Can you fix the error from testings? :)

**Comment by pariterre** [comment]
@EveCharbie  up?

**Comment by EveCharbie** [comment]
I verified the values with my python version and everything is now OK :)

**Review by pariterre — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/263#-:-N0fDYvA9qXqKmF87ukV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)

**Pull request merged**
