### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nashmit**
Clarification with respect to the inertia matrix required as input by bioMod file.

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/266)

### CODE REVIEW

**Review by pariterre — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/266)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pariterre)

**Review by pariterre — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/266)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nashmit)

**Comment by pariterre** [comment]
LGTM GG :)

**Comment by nashmit** [comment]
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/266)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nashmit)

What exactly are you waiting? :)

**Comment by pariterre** [comment]
Nothing, this is already merged :)

**Pull request merged**
