### PR TITLE
generalizing contacts to forward dynamics

### PR DESCRIPTION
**Pull request by Ipuch**
- new constructor added to utils::SpatialVector
- Public and swig version of rigidContactToSpatialVector
- Forward Dynamics can now work with contacts

@fbailly 

---
This change is [Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/278)

### CODE REVIEW

**Review by pariterre — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/278)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`src/RigidBody/Contacts.cpp` line 479 at r1](https://reviewable.io/reviews/pyomeca/biorbd/278#-N6x52z06q2ZXK9v47rY:-N6x52z06q2ZXK9v47rZ:bm2u564) ([raw file](https://github.com/pyomeca/biorbd/blob/9b180797398069f1ee9730a76e3bf48f0e838050/src/RigidBody/Contacts.cpp#L479)):*
> ```cpp
> }
> 
> std::vector<utils::SpatialVector> rigidbody::Contacts::rigidContactToSpatialVector(
> ```

This function should be tested

**Review by pariterre — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/278)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch)

___
*[`src/RigidBody/Contacts.cpp` line 507 at r1](https://reviewable.io/reviews/pyomeca/biorbd/278#-N6x5MdLBAKeLFb0UG9V:-N6x5MdLBAKeLFb0UG9W:b-oll1xw) ([raw file](https://github.com/pyomeca/biorbd/blob/9b180797398069f1ee9730a76e3bf48f0e838050/src/RigidBody/Contacts.cpp#L507)):*
> ```cpp
>         {
>             // Index of rigid contact
>             unsigned int contact_index = segmentRigidContactIdx(i)[j];
> ```

Please use `camelCase` in C/C++

**Review by Ipuch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/278)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`src/RigidBody/Contacts.cpp` line 479 at r1](https://reviewable.io/reviews/pyomeca/biorbd/278#-N6x52z06q2ZXK9v47rY:-N6xJL_R40GSrNiYk8xM:b4x4ycv) ([raw file](https://github.com/pyomeca/biorbd/blob/9b180797398069f1ee9730a76e3bf48f0e838050/src/RigidBody/Contacts.cpp#L479)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This function should be tested
</blockquote></details>

It is already tested.
___
*[`src/RigidBody/Contacts.cpp` line 507 at r1](https://reviewable.io/reviews/pyomeca/biorbd/278#-N6x5MdLBAKeLFb0UG9V:-N6xJK-j8FQxbsV6R5n0:b-896fix) ([raw file](https://github.com/pyomeca/biorbd/blob/9b180797398069f1ee9730a76e3bf48f0e838050/src/RigidBody/Contacts.cpp#L507)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please use `camelCase` in C/C++
</blockquote></details>

Done.

**Review by pariterre — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pyomeca/biorbd/278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)

**Comment by Ipuch** [comment]
@pariterre to reopen with your modifications ?

**Comment by pariterre** [comment]
It is not possible, I have opened #282

**Pull request merged**
