### PR TITLE
Wrapping objects naming issue

### PR DESCRIPTION
**Pull request by askuric**
A short PR concerning the naming issues due to changes in the `WrappingCylinder` class.
The example model and the python code are updated.
But the cpp examples should be updated too probably.

But I still have some issues with it, as far as I could understand it is due to the swig mapping.
I'll post the issue separately.

### CODE REVIEW

**Comment by pariterre** [comment]
That is correct! Thanks for pointing out

**Review by pariterre — DISMISSED** [review]
LGTM

**Comment by pariterre** [comment]
I've double check, the change you made fixed the C++ example as well since they share the bioMod file! I pushed a little fix in error message in C++ though. 

EDIT: I just realized that this file is not actually supposed to be there.. It is a relic of when I was validating the computation of the cylinders... I strongly suggest to create and use wrapping objects via the bioMod and biorbd methods, instead of calling RBDL interface! That said, if you think it makes sense to keep the example on how to modify a model on the spot, I will keep the file but update it to the new interface!

**Comment by askuric** [comment]
I see what you mean, it's really as you wish.
For me, the example itself is not that helpful in it's contents but I'd just say that it would be good to have at least one example code working with muscle wrapping, since there isn't that much docs about it.

**Comment by pariterre** [comment]
I understand.. 
As a user, what would you expect as example? I ask because, for instance, changing the model loaded in `forwardDynamicsFromMuscles.py` from `arm26.bioMod` to `WrappingObjectExample.bioMod` without changing anything else would therefore use the wrapping automatically (from the call to the `muscleForces` method)

I could add a comment at that line stating that if the model has any wrapping objects, it would automatically use them? Would that suffice?

**Comment by askuric** [comment]
Yes, sure I think that would be a good approach.
Maybe another one would be to augment the `arm26.bioMod` model to use the wrapping and then do some calculation with it, or just visualize it. If you are interested, I would volunteer for that one if you'd be interested :D

**Comment by pariterre** [comment]
That would be awesome! 
The `bioviz` will be useful for visualization as in the `inverseKinematicsKalman.py` example. It test if bioviz is installed and then plot if it is. The computation I suggest would be to print the rototranslation matrix in the console, and maybe the muscle length after moving the model? 

If you struggle in any of the step in the process, we can discuss, and afterward somehow augment the doc to response to what you struggled with. Since I wrote in C++, the doc is much more complete on the base code that it is in the binder :'(

**Review by pariterre — APPROVED** [review]
LGTM
Should I accept the PR, or you want to push your python example on this one? If so, I think it would make sense to remove the TEST....py file in example as it may lead user to think this is the intended way to use biorbd!

**Comment by askuric** [comment]
I'm still working on the example, and I'll make another PR once when its done. :smile: 
Thanks for the responsiveness!

**Review by pariterre — APPROVED** [review]
LGTM

**Pull request merged**
